GHCICMD = ghci
TESTDIR = Tests

.PHONY: test
test: 
	echo ":main " | $(GHCICMD) $(TESTDIR)/All.hs

.PHONY: esch
esch: 
	echo ":main Escher" | $(GHCICMD) Main.hs

.PHONY: gri
gri: 
	echo ":main Grilla" | $(GHCICMD) Main.hs

.PHONY: aureo
aureo: 
	echo ":main Aureo" | $(GHCICMD) Main.hs	

.PHONY: sier
sier: 
	echo ":main Sierpinski" | $(GHCICMD) Main.hs	
